### ISSUE TITLE
vertica.h is missing in your package. Compilation error

### ISSUE THREAD

**Issue by Harshaajmera** [dingqiangliu/vertica_pivot#3]
Hi dingqiangliu,
Can you please provide vertica.h and its dependent libraries also as it is included in your pivot.cpp. I get compilation error. Also, Do I have to use C++ 11 to compile?

**Comment by dingqiangliu** [comment]
C++11 is required since Vertica 9.3,  a notice is added in a498b68 .
Veritca should be installed before compiling this UDx,  header files of Vertica SDK is under /opt/vertica/sdk/include/ by default.

**Comment by Harshaajmera** [comment]
> C++11 is required since Vertica 9.3, a notice is added in [a498b68](https://github.com/dingqiangliu/vertica_pivot/commit/a498b68c14909ac4bf2116320864a9d7ba863c22) .
> Veritca should be installed before compiling this UDx, header files of Vertica SDK is under /opt/vertica/sdk/include/ by default.

We have vertica 9.2.1 version. So will it work on that?

**Comment by dingqiangliu** [comment]
c++11 is mentioned here https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/NewFeatures/9.3/9.3.0/SDKUpdates.htm, seems it also works on versions prior to 9.3.

Sorry I have no Vertica 9.2.x environment any more, if your compiler asking for standard c++11, you'd better follow it.

**Comment by Harshaajmera** [comment]
Hi, 
We have vertica 9.3 installed, with gcc compiler compatible with C++11. Here is the error we got.

n file included from /opt/vertica/sdk/include/Vertica.h:74,
                 from pivot.cpp:8:
/opt/vertica/sdk/include/BuildAssertions.h:52:10: warning: #warning "Vertica maintains C++11 compatibility, refrain from newer language features." [-Wcpp]
         #warning "Vertica maintains C++11 compatibility, refrain from newer language features."
          ^~~~~~~
In file included from /opt/vertica/sdk/include/Vertica.h:74,
                 from pivot.cpp:8:
/opt/vertica/sdk/include/BuildAssertions.h:76:10: error: #error "Vertica does not build on GCC v8.0 or above."
         #error "Vertica does not build on GCC v8.0 or above."
          ^~~~~
pivot.cpp: In member function ‘virtual void Pivot::setup(Vertica::ServerInterface&, const Vertica::SizedColumnTypes&)’:
pivot.cpp:71:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if (paramReader.containsParameter("method"))
         ^~
pivot.cpp:73:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
             std::transform(method.begin(), method.end(), method.begin(), ::toupper);
             ^~~
pivot.cpp: In member function ‘virtual void Pivot::processPartition(Vertica::ServerInterface&, Vertica::PartitionReader&, Vertica::PartitionWriter&)’:
pivot.cpp:222:39: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
         if (input_reader.getNumCols() != measureCount + 1)
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
pivot.cpp: In member function ‘virtual void PivotFactory::getReturnType(Vertica::ServerInterface&, const Vertica::SizedColumnTypes&, Vertica::SizedColumnTypes&)’:
pivot.cpp:347:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if (paramReader.containsParameter("method"))
         ^~
pivot.cpp:349:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
             std::transform(method.begin(), method.end(), method.begin(), ::toupper);
             ^~~
In file included from /opt/vertica/sdk/include/Vertica.h:74,
                 from /opt/vertica/sdk/include/Vertica.cpp:38:
/opt/vertica/sdk/include/BuildAssertions.h:52:10: warning: #warning "Vertica maintains C++11 compatibility, refrain from newer language features." [-Wcpp]
         #warning "Vertica maintains C++11 compatibility, refrain from newer language features."
          ^~~~~~~
In file included from /opt/vertica/sdk/include/Vertica.h:74,
                 from /opt/vertica/sdk/include/Vertica.cpp:38:
/opt/vertica/sdk/include/BuildAssertions.h:76:10: error: #error "Vertica does not build on GCC v8.0 or above."
         #error "Vertica does not build on GCC v8.0 or above."
          ^~~~~

Can you please help in this.

**Comment by dingqiangliu** [comment]
@Harshaajmera please build whith following commands:
```SH
./configure CXXFLAGS='-std=c++11' && make
```

**Comment by Harshaajmera** [comment]
We followed the steps you said but got bellow errors

1.
badmin@~]$ g++ --std=c++11 pivot.cpp -o pivot.o
pivot.cpp:8:10: fatal error: Vertica.h: No such file or directory
#include "Vertica.h"
          ^~~~~~~~~~~
compilation terminated.
2.
[dbadmin@ ~]$  g++ --std=c++11 -D HAVE_LONG_INT_64 -I /opt/vertica/sdk/include -Wall -shared -Wno-unused-value -fPIC -o /home/dbadmin/pivot.so pivot.cpp /opt/vertica/sdk/include/Vertica.cpp
In file included from /opt/vertica/sdk/include/Vertica.h:74,
                 from pivot.cpp:8:
/opt/vertica/sdk/include/BuildAssertions.h:76:10: error: #error "Vertica does not build on GCC v8.0 or above."
         #error "Vertica does not build on GCC v8.0 or above."
pivot.cpp: In member function ‘virtual void Pivot::setup(Vertica::ServerInterface&, const Vertica::SizedColumnTypes&)’:
pivot.cpp:71:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if (paramReader.containsParameter("method"))
         ^~
pivot.cpp:73:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
             std::transform(method.begin(), method.end(), method.begin(), ::toupper);
             ^~~
pivot.cpp: In member function ‘virtual void Pivot::processPartition(Vertica::ServerInterface&, Vertica::PartitionReader&, Vertica::PartitionWriter&)’:
pivot.cpp:222:39: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
         if (input_reader.getNumCols() != measureCount + 1)
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
pivot.cpp: In member function ‘virtual void PivotFactory::getReturnType(Vertica::ServerInterface&, const Vertica::SizedColumnTypes&, Vertica::SizedColumnTypes&)’:
pivot.cpp:347:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if (paramReader.containsParameter("method"))
         ^~
pivot.cpp:349:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
             std::transform(method.begin(), method.end(), method.begin(), ::toupper);
             ^~~
In file included from /opt/vertica/sdk/include/Vertica.h:74,
                 from /opt/vertica/sdk/include/Vertica.cpp:38:
/opt/vertica/sdk/include/BuildAssertions.h:76:10: error: #error "Vertica does not build on GCC v8.0 or above."
         #error "Vertica does not build on GCC v8.0 or above."

**Comment by dingqiangliu** [comment]
Could you try lower version of GCC as it said "Vertica does not build on GCC v8.0 or above".

**Comment by dingqiangliu** [comment]
@Harshaajmera Could you try lower version of GCC as it said "Vertica does not build on GCC v8.0 or above"?
BTW, I only tested on Centos 7 with gcc-4.8.5 .
